package ink

// ChoicePoint represents a point in the story generated by the compiler
// where a choice can be taken.
type ChoicePoint struct {
	BaseRuntimeObject
	PathStringOnChoice   string
	HasCondition         bool
	HasStartContent      bool
	HasChoiceOnlyContent bool
	IsInvisibleDefault   bool
	OnceOnly             bool
}

// NewChoicePoint creates a new ChoicePoint.
func NewChoicePoint(hasCondition bool, hasStartContent bool, hasChoiceOnlyContent bool, onceOnly bool, isInvisibleDefault bool) *ChoicePoint {
	return &ChoicePoint{
		BaseRuntimeObject:    *NewBaseRuntimeObject(),
		HasCondition:         hasCondition,
		HasStartContent:      hasStartContent,
		HasChoiceOnlyContent: hasChoiceOnlyContent,
		OnceOnly:             onceOnly,
		IsInvisibleDefault:   isInvisibleDefault,
	}
}

// PathStringOnChoice returns the path string.
func (c *ChoicePoint) GetPathStringOnChoice() string {
	return c.PathStringOnChoice
}

// Flags returns the flags for serialization.
func (c *ChoicePoint) Flags() int {
	flags := 0
	if c.HasCondition {
		flags |= 1
	}
	if c.HasStartContent {
		flags |= 2
	}
	if c.HasChoiceOnlyContent {
		flags |= 4
	}
	if c.IsInvisibleDefault {
		flags |= 8
	}
	if c.OnceOnly {
		flags |= 16
	}
	return flags
}

// SetPathStringOnChoice sets the path string.
func (c *ChoicePoint) SetPathStringOnChoice(pathStr string) {
	c.PathStringOnChoice = pathStr
}

// Flags needed for parsing
func (c *ChoicePoint) SetFlags(flags int) {
	c.HasCondition = (flags & 1) > 0
	c.HasStartContent = (flags & 2) > 0
	c.HasChoiceOnlyContent = (flags & 4) > 0
	c.IsInvisibleDefault = (flags & 8) > 0
	c.OnceOnly = (flags & 16) > 0
}

func (c *ChoicePoint) GetFlags() int {
	flags := 0
	if c.HasCondition {
		flags |= 1
	}
	if c.HasStartContent {
		flags |= 2
	}
	if c.HasChoiceOnlyContent {
		flags |= 4
	}
	if c.IsInvisibleDefault {
		flags |= 8
	}
	if c.OnceOnly {
		flags |= 16
	}
	return flags
}

func (c *ChoicePoint) String() string {
	// For debugging
	return "ChoicePoint(" + c.PathStringOnChoice + ")"
}
